// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD043SmYwZLJsaACRvhJuKF8UdehtL7Cro',
    appId: '1:370638179991:web:c11e7ab84394b9939ca3d2',
    messagingSenderId: '370638179991',
    projectId: 'project-akhir-bpc',
    authDomain: 'project-akhir-bpc.firebaseapp.com',
    storageBucket: 'project-akhir-bpc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAItRM_9gdIymCSdwOw9QIpsl393ONfMDw',
    appId: '1:370638179991:android:d48b47dcfb54cc829ca3d2',
    messagingSenderId: '370638179991',
    projectId: 'project-akhir-bpc',
    storageBucket: 'project-akhir-bpc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD043SmYwZLJsaACRvhJuKF8UdehtL7Cro',
    appId: '1:370638179991:web:d86534a0955a1da09ca3d2',
    messagingSenderId: '370638179991',
    projectId: 'project-akhir-bpc',
    authDomain: 'project-akhir-bpc.firebaseapp.com',
    storageBucket: 'project-akhir-bpc.firebasestorage.app',
  );
}
